# Multi-stage image for miniflux-feed-dedup
# Generated by genproj (docker-container capability, language-aware). Adjust
# for your application.
#
# Stage 1 (build): copies the full source tree, installs dependencies and
# builds the application. Stage 2 (runtime): copies only the build output /
# virtualenv and production dependencies, keeping the final image small.

FROM python:3.12-alpine AS build
WORKDIR /app
COPY README.md pyproject.toml* requirements.txt* ./
RUN python -m venv /opt/venv \
    && /opt/venv/bin/pip install --upgrade pip \
    && mkdir -p src/miniflux_feed_dedup && touch src/miniflux_feed_dedup/__init__.py \
    && if [ -f requirements.txt ]; then \
         grep -vE '^\s*(-e|--editable)\s+\.' requirements.txt > /tmp/reqs.txt || true; \
         [ -s /tmp/reqs.txt ] && /opt/venv/bin/pip install --no-cache-dir -r /tmp/reqs.txt; \
       fi \
    && if [ -f pyproject.toml ]; then \
         /opt/venv/bin/pip install --no-cache-dir .; \
       fi
COPY . .
RUN if [ -f requirements.txt ]; then \
      /opt/venv/bin/pip install --no-cache-dir -r requirements.txt; \
    elif [ -f pyproject.toml ]; then \
      /opt/venv/bin/pip install --no-cache-dir --no-deps .; \
    fi

FROM python:3.12-alpine
WORKDIR /app
# Link the GHCR container package to its GitHub repo on push. GHCR auto-links
# the package to nickbrett1/miniflux-feed-dedup so it inherits the
# repo's access (public repo -> public package; no manual visibility step).
LABEL org.opencontainers.image.source=https://github.com/nickbrett1/miniflux-feed-dedup
RUN apt-get update && apt-get install -y --no-install-recommends curl \
    && rm -rf /var/lib/apt/lists/*
ENV PATH="/opt/venv/bin:$PATH"
COPY --from=build /opt/venv /opt/venv
COPY . .
EXPOSE 8090

HEALTHCHECK --interval=30s --timeout=3s --start-period=10s CMD curl -fsS http://127.0.0.1:8090/healthz || exit 1
CMD ["python", "-m", "miniflux_feed_dedup"]
